# Generated by Django 3.2.5 on 2021-09-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
